apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibamail-tls
spec:
  dnsNames:
    - kibamail.com
    - www.kibamail.com
    - auth.kibamail.com
    - admin.auth.kibamail.com
    - api.kibamail.com
