apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibamail-control-plane
spec:
  hostnames:
    - kibamail.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibamail-marketing
spec:
  hostnames:
    - kibamail.com
    - www.kibamail.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibamail-api
spec:
  hostnames:
    - api.kibamail.com
