# NATS Role Handlers
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart nats
  ansible.builtin.systemd:
    name: nats
    state: restarted
  when: nats_start_result is defined

- name: Reload nats
  ansible.builtin.command: >
    /usr/local/bin/nats-server --signal reload
  changed_when: true
