'use client'

import * as Tabs from '@radix-ui/react-tabs'
import { Copy } from 'iconoir-react'
import type { PropsWithChildren, ReactNode } from 'react'

interface SdkCodeSnippetsProps {
  footer?: ReactNode
  sdks: { name: string; code: string }[]
}

export function SdkCodeSnippets({
  footer,
  sdks,
  children,
}: PropsWithChildren<SdkCodeSnippetsProps>) {
  return (
    <Tabs.Root defaultValue={sdks?.[0]?.name}>
      <div className="w-full flex flex-col rounded-2xl border border-gray-950/10 dark:border-white/10">
        <div className="min-h-13 py-3 flex items-center justify-between rounded-t-2xl bg-gray-50 dark:bg-gray-900 border-b border-gray-950/10 dark:border-white/10 px-3">
          <Tabs.List className="flex items-center gap-2">
            {sdks.map((sdk) => (
              <Tabs.Trigger
                value={sdk.name}
                key={sdk.name}
                className="cursor-pointer text-gray-600 dark:text-gray-400 font-medium border-transparent data-[state=active]:border data-[state=active]:border-solid data-[state=active]:border-gray-950/10 dark:data-[state=active]:border-white/10 data-[state=active]:text-gray-950 dark:data-[state=active]:text-white rounded-lg px-2 py-1"
              >
                {sdk.name}
              </Tabs.Trigger>
            ))}
          </Tabs.List>

          <Copy className="text-gray-600 dark:text-gray-400 w-5 h-5" />
        </div>

        <div className="w-full overflow-x-auto bg-[#212121]">
          {sdks.map(({ name, code }) => (
            <Tabs.Content value={name} key={name}>
              {/* biome-ignore lint/security/noDangerouslySetInnerHtml: code snippets are generated by us on the server, and not by users, so this is safe. */}
              <div dangerouslySetInnerHTML={{ __html: code }} />
            </Tabs.Content>
          ))}
        </div>

        {footer && (
          <div className="min-h-13 py-3 flex items-center rounded-b-2xl justify-between bg-gray-50 dark:bg-gray-900 border-t border-gray-950/10 dark:border-white/10 px-3">
            {footer}
          </div>
        )}
      </div>
    </Tabs.Root>
  )
}

