apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
  - postgres-secrets.yaml
  - backup-secrets.yaml
  - objectstore.yaml
  - cnpg-custom-monitoring.yaml
  - cluster.yaml
  - pooler.yaml
  # - podmonitor.yaml  # Not needed - using SigNoz k8s-infra Prometheus scraping
  - scheduled-backup.yaml
