apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
  - postgres-secrets.yaml
  - backup-secrets.yaml
  - objectstore.yaml
  - cluster.yaml
  - pooler.yaml
  # - podmonitor.yaml  # Requires Prometheus Operator
  - scheduled-backup.yaml
