apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: kibamail-backup-store
spec:
  configuration:
    destinationPath: s3://staging-kibamail-com-postgres-backups/
    endpointURL: https://e61cebd91eb54d4ebeec9c5d525ae041.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: postgres-backup-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: postgres-backup-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  retentionPolicy: "30d"
