apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kibamail-postgres-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: kibamail-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: kibamail
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: POSTGRES_PASSWORD
