apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibamail-tls
  namespace: kibamail
spec:
  secretName: kibamail-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - kibamail.com
    - www.kibamail.com
    - api.kibamail.com
    - forms.kibamail.com
