apiVersion: v1
kind: Service
metadata:
  name: kibamail-web-internal
  namespace: kibamail
  labels:
    app.kubernetes.io/name: kibamail-web
    app.kubernetes.io/component: web-internal
    app.kubernetes.io/part-of: kibamail
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: cp-http
      nodePort: 30300
      protocol: TCP
  selector:
    app.kubernetes.io/name: kibamail-web
