apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets
  - storage
  - ingress
  - postgres
  - rabbitmq
  - valkey
  - outpost
  - logto
  - certificates
  - kibamail-control-plane
  - kibamail-marketing
  - kibamail-api
  - kibamail-workers
  - deployment-rbac
  - signoz-infra
