apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-credentials
  namespace: kibamail-tracking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: control-plane-credentials
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: CONTROL_PLANE_APP_KEY
    - secretKey: INTERNAL_SERVICE_KEY
      remoteRef:
        key: CONTROL_PLANE_INTERNAL_SERVICE_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-valkey
  namespace: kibamail-tracking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-valkey
    kind: ClusterSecretStore
  target:
    name: control-plane-valkey
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kibamail-valkey
