apiVersion: v1
kind: Service
metadata:
  name: kibamail-tracking
  namespace: kibamail-tracking
  labels:
    app.kubernetes.io/name: kibamail-tracking
    app.kubernetes.io/component: tracking
    app.kubernetes.io/part-of: kibamail
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: kibamail-tracking
