# tracking Role Handlers
---
- name: Reload OpenResty
  ansible.builtin.systemd:
    name: openresty
    state: reloaded

- name: Restart OpenResty
  ansible.builtin.systemd:
    name: openresty
    state: restarted

- name: Restart PM2 tracking
  ansible.builtin.command: pm2 reload tracking
  become_user: "{{ tracking_user }}"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
