apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deployer
  namespace: kibamail-deployments
---
apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-token
  namespace: kibamail-deployments
  annotations:
    kubernetes.io/service-account.name: github-deployer
type: kubernetes.io/service-account-token
