-- AlterTable
ALTER TABLE `automations` MODIFY `triggerType` ENUM('CONTACT_SUBSCRIBED', 'PROPERTY_UPDATED', 'FORM_SUBMITTED', 'API', 'EVENT', 'SEGMENT_ENTRY', 'SEGMENT_EXIT', 'EMAIL_ENGAGEMENT') NOT NULL;
