apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: kibamail-valkey
  labels:
    app.kubernetes.io/name: kibamail-valkey
    app.kubernetes.io/part-of: kibamail
spec:
  nodes: 3
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  tls: false
  externalAccess:
    enabled: false
  volumePermissions: true
  image: ghcr.io/hyperspike/valkey:8.1.4
  exporterImage: ghcr.io/hyperspike/valkey-sidecar:v0.0.61
  prometheus: false
  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: kibamail-storage
