apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-postgres
  namespace: kibamail-event-ingestor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: control-plane-postgres
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: CONTROL_PLANE_DATABASE_URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-valkey
  namespace: kibamail-event-ingestor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-valkey
    kind: ClusterSecretStore
  target:
    name: control-plane-valkey
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kibamail-valkey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-nats
  namespace: kibamail-event-ingestor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: control-plane-nats
    creationPolicy: Owner
  data:
    - secretKey: NATS_URL
      remoteRef:
        key: CONTROL_PLANE_NATS_URL
    - secretKey: NATS_USER
      remoteRef:
        key: CONTROL_PLANE_NATS_USER
    - secretKey: NATS_PASSWORD
      remoteRef:
        key: CONTROL_PLANE_NATS_PASSWORD
    - secretKey: NATS_TLS_CA
      remoteRef:
        key: CONTROL_PLANE_NATS_TLS_CA
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-credentials
  namespace: kibamail-event-ingestor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: control-plane-credentials
    creationPolicy: Owner
  data:
    - secretKey: OTEL_INGESTION_API_KEY
      remoteRef:
        key: OTEL_INGESTION_API_KEY
