-- CreateTable
CREATE TABLE `forms` (
    `id` VARCHAR(191) NOT NULL,
    `workspaceId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,
    `status` ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    `version` INTEGER NOT NULL DEFAULT 1,
    `parentId` VARCHAR(191) NULL,
    `fields` JSON NOT NULL,
    `settings` JSON NULL,
    `publishedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deleted_at` DATETIME(3) NULL,

    INDEX `forms_workspaceId_idx`(`workspaceId`),
    INDEX `forms_workspaceId_status_idx`(`workspaceId`, `status`),
    INDEX `forms_workspaceId_deleted_at_idx`(`workspaceId`, `deleted_at`),
    INDEX `forms_parentId_idx`(`parentId`),
    INDEX `forms_status_idx`(`status`),
    INDEX `forms_version_idx`(`version`),
    UNIQUE INDEX `forms_workspaceId_parentId_status_key`(`workspaceId`, `parentId`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `form_submissions` (
    `id` VARCHAR(191) NOT NULL,
    `formId` VARCHAR(191) NOT NULL,
    `workspaceId` VARCHAR(191) NOT NULL,
    `contactId` VARCHAR(191) NULL,
    `status` ENUM('PENDING', 'PROCESSED', 'SPAM', 'FAILED') NOT NULL DEFAULT 'PENDING',
    `ipAddress` VARCHAR(191) NULL,
    `userAgent` TEXT NULL,
    `referrerUrl` TEXT NULL,
    `landingPageUrl` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `fieldString0` VARCHAR(255) NULL,
    `fieldString1` VARCHAR(255) NULL,
    `fieldString2` VARCHAR(255) NULL,
    `fieldString3` VARCHAR(255) NULL,
    `fieldString4` VARCHAR(255) NULL,
    `fieldString5` VARCHAR(255) NULL,
    `fieldString6` VARCHAR(255) NULL,
    `fieldString7` VARCHAR(255) NULL,
    `fieldString8` VARCHAR(255) NULL,
    `fieldString9` VARCHAR(255) NULL,
    `fieldString10` VARCHAR(255) NULL,
    `fieldString11` VARCHAR(255) NULL,
    `fieldString12` VARCHAR(255) NULL,
    `fieldString13` VARCHAR(255) NULL,
    `fieldString14` VARCHAR(255) NULL,
    `fieldString15` VARCHAR(255) NULL,
    `fieldString16` VARCHAR(255) NULL,
    `fieldString17` VARCHAR(255) NULL,
    `fieldString18` VARCHAR(255) NULL,
    `fieldString19` VARCHAR(255) NULL,
    `fieldString20` VARCHAR(255) NULL,
    `fieldString21` VARCHAR(255) NULL,
    `fieldString22` VARCHAR(255) NULL,
    `fieldString23` VARCHAR(255) NULL,
    `fieldString24` VARCHAR(255) NULL,
    `fieldString25` VARCHAR(255) NULL,
    `fieldString26` VARCHAR(255) NULL,
    `fieldString27` VARCHAR(255) NULL,
    `fieldString28` VARCHAR(255) NULL,
    `fieldString29` VARCHAR(255) NULL,
    `fieldNum0` DOUBLE NULL,
    `fieldNum1` DOUBLE NULL,
    `fieldNum2` DOUBLE NULL,
    `fieldNum3` DOUBLE NULL,
    `fieldNum4` DOUBLE NULL,
    `fieldNum5` DOUBLE NULL,
    `fieldNum6` DOUBLE NULL,
    `fieldNum7` DOUBLE NULL,
    `fieldNum8` DOUBLE NULL,
    `fieldNum9` DOUBLE NULL,
    `fieldNum10` DOUBLE NULL,
    `fieldNum11` DOUBLE NULL,
    `fieldNum12` DOUBLE NULL,
    `fieldNum13` DOUBLE NULL,
    `fieldNum14` DOUBLE NULL,
    `fieldNum15` DOUBLE NULL,
    `fieldNum16` DOUBLE NULL,
    `fieldNum17` DOUBLE NULL,
    `fieldNum18` DOUBLE NULL,
    `fieldNum19` DOUBLE NULL,
    `fieldNum20` DOUBLE NULL,
    `fieldNum21` DOUBLE NULL,
    `fieldNum22` DOUBLE NULL,
    `fieldNum23` DOUBLE NULL,
    `fieldNum24` DOUBLE NULL,

    INDEX `form_submissions_workspaceId_idx`(`workspaceId`),
    INDEX `form_submissions_formId_idx`(`formId`),
    INDEX `form_submissions_contactId_idx`(`contactId`),
    INDEX `form_submissions_status_idx`(`status`),
    INDEX `form_submissions_createdAt_idx`(`createdAt`),
    INDEX `form_submissions_workspaceId_fieldString0_idx`(`workspaceId`, `fieldString0`),
    INDEX `form_submissions_workspaceId_fieldString1_idx`(`workspaceId`, `fieldString1`),
    INDEX `form_submissions_workspaceId_fieldString2_idx`(`workspaceId`, `fieldString2`),
    INDEX `form_submissions_workspaceId_fieldString3_idx`(`workspaceId`, `fieldString3`),
    INDEX `form_submissions_workspaceId_fieldString4_idx`(`workspaceId`, `fieldString4`),
    INDEX `form_submissions_workspaceId_fieldNum0_idx`(`workspaceId`, `fieldNum0`),
    INDEX `form_submissions_workspaceId_fieldNum1_idx`(`workspaceId`, `fieldNum1`),
    INDEX `form_submissions_workspaceId_fieldNum2_idx`(`workspaceId`, `fieldNum2`),
    INDEX `form_submissions_workspaceId_fieldNum3_idx`(`workspaceId`, `fieldNum3`),
    INDEX `form_submissions_workspaceId_fieldNum4_idx`(`workspaceId`, `fieldNum4`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `forms` ADD CONSTRAINT `forms_parentId_fkey` FOREIGN KEY (`parentId`) REFERENCES `forms`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `form_submissions` ADD CONSTRAINT `form_submissions_formId_fkey` FOREIGN KEY (`formId`) REFERENCES `forms`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
