export default {
  "Marketing email": {
    routes: [
      ["Getting started", "/marketing/getting-started"],
      ["Dashboard overview", "/marketing/dashboard"],
      ["Creating campaigns", "/marketing/campaigns/creating"],
      ["Email templates", "/marketing/campaigns/templates"],
      ["A/B testing", "/marketing/campaigns/ab-testing"],
      ["Scheduling campaigns", "/marketing/campaigns/scheduling"],
      ["Contact management", "/marketing/contacts/management"],
      ["Contact lists", "/marketing/contacts/lists"],
      ["Segmentation", "/marketing/contacts/segmentation"],
      ["Import & export", "/marketing/contacts/import-export"],
      ["Automation workflows", "/marketing/automation/workflows"],
      ["Triggers & conditions", "/marketing/automation/triggers"],
      ["Welcome series", "/marketing/automation/welcome-series"],
      ["Drip campaigns", "/marketing/automation/drip-campaigns"],
      ["Email composer", "/marketing/composer/editor"],
      ["Template library", "/marketing/composer/templates"],
      ["Dynamic content", "/marketing/composer/dynamic-content"],
      ["Personalization", "/marketing/composer/personalization"],
      ["Campaign analytics", "/marketing/analytics/campaigns"],
      ["Engagement metrics", "/marketing/analytics/engagement"],
      ["Revenue tracking", "/marketing/analytics/revenue"],
      ["Custom reports", "/marketing/analytics/reports"],
    ] as const,
  },
  "Transactional email": {
    routes: [
      ["Getting started", "/transactional/getting-started"],
      ["API integration", "/transactional/api-integration"],
      ["Email types", "/transactional/email-types"],
      ["Template management", "/transactional/templates"],
      ["Dynamic templates", "/transactional/dynamic-templates"],
      ["Personalization", "/transactional/personalization"],
      ["Delivery settings", "/transactional/delivery"],
      ["Webhooks", "/transactional/webhooks"],
      ["Testing emails", "/transactional/testing"],
      ["Monitoring & logs", "/transactional/monitoring"],
      ["Delivery analytics", "/transactional/analytics"],
      ["Error handling", "/transactional/error-handling"],
      ["Best practices", "/transactional/best-practices"],
      ["Compliance", "/transactional/compliance"],
    ] as const,
  },
} as const;
