/**
 * Queue Type Definitions
 *
 * Define your queues and their jobs here for type safety across the application.
 *
 * Example:
 * ```ts
 * export type QueueJobs = {
 *   'email': {
 *     'send-welcome': { userId: string; email: string };
 *     'send-notification': { userId: string; message: string };
 *   };
 *   'data-processing': {
 *     'import-contacts': { workspaceId: string; fileUrl: string };
 *     'export-data': { workspaceId: string; format: 'csv' | 'json' };
 *   };
 * };
 * ```
 */

/**
 * Queue Jobs Type Map
 *
 * Add your queues and their jobs here. The structure is:
 * {
 *   'queue-name': {
 *     'job-name': JobDataType;
 *   }
 * }
 */
export type QueueJobs = {
  // Example queue - remove or replace with your actual queues
  example: {
    "example-job": { message: string };
  };
  // Segments queue for segment-related background jobs
  segments: {
    "compute-contacts-count": { segmentIds: string[] };
  };
  // Contact imports queue for processing CSV imports
  "contact-imports": {
    "process-import": { contactImportId: string };
  };
  // Broadcasts queue for sending broadcasts
  broadcasts: {
    "send-broadcast": { broadcastId: string };
    "send-broadcast-batch": {
      broadcastId: string;
      batchId: string;
      contactIds: string[];
      contacts?: Array<{
        id: string;
        email: string;
        firstName: string | null;
        lastName: string | null;
        properties: Record<string, string | number | Date | null>;
      }>;
    };
    "send-test-broadcast": {
      broadcastId: string;
      testEmails: string[];
    };
  };
  // Sending domains queue for domain verification checks
  "sending-domains": {
    "check-verification": { domainId: string; attempt: number };
    "check-tracking-dns": { domainId: string; attempt?: number };
    "issue-tracking-ssl": { domainId: string };
    "renew-expiring-ssl": Record<string, never>;
  };
  // Forms queue for form-related background jobs
  forms: {
    "send-double-opt-in": {
      contactId: string;
      formId: string;
      emailId: string;
      workspaceId: string;
    };
    "confirm-double-opt-in": {
      formId: string;
      confirmationToken: string;
    };
  };
  // Contacts queue for contact-related background jobs
  contacts: {
    unsubscribe: {
      contactId: string;
      broadcastId: string;
      source: "link" | "list-unsubscribe";
    };
  };
  // Inbox queue for processing inbound emails and sending replies
  inbox: {
    "process-inbound-email": {
      /** Request ID for end-to-end tracing (generated by MTA) */
      requestId: string;
      /** The emailSendId token from the plus-addressed recipient */
      token: string;
      /** S3 key where the raw email is stored */
      s3Key: string;
      /** Sender email address */
      sender: string;
      /** Full recipient email address */
      recipient: string;
      /** Workspace ID */
      workspaceId: string;
      /** Sending domain ID */
      sendingDomainId: string;
      /** ISO timestamp when the email was received */
      receivedAt: string;
    };
    "send-reply": {
      /** Conversation ID to reply to */
      conversationId: string;
      /** HTML content of the reply */
      replyContent: string;
      /** Optional subject override */
      replySubject?: string;
    };
  };
  // Emails queue for transactional email sending
  emails: {
    "send-transactional": {
      /** Unique ID for this email send */
      emailSendId: string;
      /** Workspace ID */
      workspaceId: string;
      /** Sender identity ID */
      senderIdentityId: string;
      /** Sending domain ID */
      sendingDomainId: string;
      /** Optional reply-to configuration */
      replyTo?: {
        email: string;
        name?: string;
      };
      /** Recipient email(s) - single or array */
      to: string | string[];
      /** Email subject */
      subject: string;
      /** Preview text shown in email clients (optional) */
      previewText?: string;
      /** HTML body */
      htmlBody: string;
      /** Plain text body (optional) */
      textBody?: string;
      /** Attachments with base64 content (uploaded in background job) */
      attachments?: Array<{
        filename: string;
        contentType: string;
        content: string;
        index: number;
      }>;
      /** Custom metadata for tracking */
      metadata?: Record<string, string>;
    };
  };
};

/**
 * Extract queue names from QueueJobs
 */
export type QueueName = keyof QueueJobs;

/**
 * Extract job names for a specific queue
 */
export type JobName<Q extends QueueName> = keyof QueueJobs[Q] & string;

/**
 * Extract job data type for a specific queue and job
 */
export type JobData<
  Q extends QueueName,
  J extends JobName<Q>,
> = QueueJobs[Q][J];

/**
 * Job options that can be passed when pushing a job to the queue
 */
export interface JobOptions {
  /**
   * Job priority (higher number = higher priority)
   */
  priority?: number;

  /**
   * Delay in milliseconds before the job is processed
   */
  delay?: number;

  /**
   * Number of attempts before the job is marked as failed
   */
  attempts?: number;

  /**
   * Backoff strategy for retries
   */
  backoff?: {
    type: "exponential" | "fixed";
    delay: number;
  };

  /**
   * Remove the job from the queue when it completes
   */
  removeOnComplete?: boolean | number;

  /**
   * Remove the job from the queue when it fails
   */
  removeOnFail?: boolean | number;
}

/**
 * Worker processor function type
 */
export type JobProcessor<Q extends QueueName, J extends JobName<Q>> = (
  data: JobData<Q, J>,
  jobId: string,
) => Promise<void>;

/**
 * Worker configuration
 */
export interface WorkerConfig<Q extends QueueName> {
  /**
   * Job processors map
   */
  processors: {
    [J in JobName<Q>]: JobProcessor<Q, J>;
  };

  /**
   * Number of concurrent jobs to process
   */
  concurrency?: number;

  /**
   * Rate limiter configuration
   */
  rateLimiter?: {
    max: number;
    duration: number;
  };
}
