# SigNoz Infrastructure namespace
# Note: This namespace is also created by the SigNoz k8s-infra Helm chart.
# We define it here to ensure Kustomize can apply resources to it.
apiVersion: v1
kind: Namespace
metadata:
  name: signoz-infra
  labels:
    app.kubernetes.io/name: signoz-infra
    app.kubernetes.io/part-of: kibamail-monitoring
