apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tracking-tls
  namespace: kibamail-tracking
spec:
  secretName: tracking-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - e.kbmta.net
