# Helsinki Production Cluster Inventory
#
# MTA cluster located at Hostkey (EU-NORTH-1)
# Primary IP: 205.172.59.37
#
---
all:
  children:
    mta:
      hosts:
        mta-1:
          ansible_host: 205.172.59.37
          ansible_user: root
          ansible_ssh_private_key_file: "{{ inventory_dir }}/secrets/id_ed25519"
          mta_node_index: 1

    k8s_cluster:
      hosts:
        node-1:
          ansible_host: 135.181.79.109
          ansible_user: root
          ansible_ssh_private_key_file: "{{ inventory_dir }}/secrets/id_ed25519"
