apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      secretsScope:
        projectSlug: staging-kibamail-com-fw-xz
        environmentSlug: staging
