apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mta-sink.yaml

patches:
  - path: certificate-patch.yaml
  - path: rabbitmq-patch.yaml
  - path: kibamail-routes-patch.yaml
  - path: kibamail-images-patch.yaml
  - path: kibamail-env-patch.yaml
  - path: cluster-secret-store-patch.yaml
  - path: logto-routes-patch.yaml
  - path: logto-deployment-patch.yaml
  - path: postgres-objectstore-patch.yaml
  - path: outpost-deployment-patch.yaml
