apiVersion: apps/v1
kind: Deployment
metadata:
  name: logto
spec:
  template:
    spec:
      containers:
        - name: logto
          env:
            - name: ENDPOINT
              value: "https://auth.staging.kibamail.com"
            - name: ADMIN_ENDPOINT
              value: "https://admin.auth.staging.kibamail.com"
            - name: OTEL_SDK_DISABLED
              value: "true"
