apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-monitor-agent
  namespace: kibamail-agent-monitor
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-monitor-agent-token
  namespace: kibamail-agent-monitor
  annotations:
    kubernetes.io/service-account.name: cluster-monitor-agent
type: kubernetes.io/service-account-token
