apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logto

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - routes.yaml
  - reference-grant.yaml
