apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logto-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: logto-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_URL: "postgres://kibamail:{{ .password }}@kibamail-postgres-rw.cnpg-system.svc.cluster.local:5432/logto"
  data:
    - secretKey: password
      remoteRef:
        key: POSTGRES_PASSWORD
