apiVersion: v1
kind: Service
metadata:
  name: logto
  labels:
    app.kubernetes.io/name: logto
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: kibamail
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: logto
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: internal-main
      port: 3001
      targetPort: http-main
      protocol: TCP
    - name: internal-admin
      port: 3002
      targetPort: http-admin
      protocol: TCP
