apiVersion: v1
kind: ConfigMap
metadata:
  name: outpost-config
  labels:
    app.kubernetes.io/name: outpost
    app.kubernetes.io/part-of: kibamail
data:
  config.yaml: |
    topics:
      - contact.created
      - contact.updated
      - contact.deleted

    mqs:
      delivery_retry_limit: 10
      log_retry_limit: 10

    destinations:
      webhook:
        header_prefix: "x-kibamail-"
