apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outpost-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: outpost-credentials
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: OUTPOST_API_KEY
    - secretKey: API_JWT_SECRET
      remoteRef:
        key: OUTPOST_API_JWT_SECRET
    - secretKey: AES_ENCRYPTION_SECRET
      remoteRef:
        key: OUTPOST_AES_ENCRYPTION_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outpost-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: outpost-postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URL
      remoteRef:
        key: OUTPOST_POSTGRES_URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outpost-rabbitmq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-rabbitmq
    kind: ClusterSecretStore
  target:
    name: outpost-rabbitmq
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RABBITMQ_SERVER_URL: "amqp://{{ .username }}:{{ .password }}@kibamail-rabbitmq.kibamail-rabbitmq.svc.cluster.local:5672"
  data:
    - secretKey: username
      remoteRef:
        key: kibamail-rabbitmq-default-user
        property: username
    - secretKey: password
      remoteRef:
        key: kibamail-rabbitmq-default-user
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outpost-valkey-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-valkey
    kind: ClusterSecretStore
  target:
    name: outpost-valkey-password
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kibamail-valkey
