# OpenTelemetry Collector Handlers
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart otel-collector
  ansible.builtin.systemd:
    name: otel-collector
    state: restarted
  when: otel_collector_start_service | default(true)
