apiVersion: v1
kind: Service
metadata:
  name: kibamail-control-plane
  labels:
    app.kubernetes.io/name: kibamail-control-plane
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: kibamail
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibamail-control-plane
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
