apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: infisical-auth
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: staging-kibamail-com-fw-xz
        environmentSlug: staging
        secretsPath: /
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-valkey
spec:
  provider:
    kubernetes:
      remoteNamespace: kibamail-valkey
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-rabbitmq
spec:
  provider:
    kubernetes:
      remoteNamespace: kibamail-rabbitmq
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
