apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-valkey-reader
  namespace: kibamail-valkey
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-valkey-reader
  namespace: kibamail-valkey
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: Role
  name: external-secrets-valkey-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-rabbitmq-reader
  namespace: kibamail-rabbitmq
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rabbitmq-reader
  namespace: kibamail-rabbitmq
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: Role
  name: external-secrets-rabbitmq-reader
  apiGroup: rbac.authorization.k8s.io
